version: 7.0.{build}

branches:
  only:
  - master

clone_folder: C:\Manam

image: Visual Studio 2019

configuration: Debug

platform: x64

before_build:
- cmd: >-
    chcp 1250

    vcpkg install --triplet=x64-windows-static

    nuget install Oracle.ManagedDataAccess -version 12.2.1100

    copy Oracle.ManagedDataAccess.12.2.1100\lib\net40\Oracle.ManagedDataAccess.dll .

build:
  project: Manam.vcxproj
  verbosity: normal
