
#pragma once

#define IDR_MAINFRAME                   1
#define IDR_DRAWCLTYPE                  2
#define IDB_SIGN                        3
#define IDEMISJE                        4
#define IDC_CAB                         5
#define IDDELALL                        6
#define IDDELSEL                        7
#define IDQUE                           8
#define IDATEX                          9
#define ID_FULLSCREEN                   10
#define ID_DRAW_ADD                     11
#define ID_DRAW_RED                     12
#define ID_DRAW_LOCK                    13
#define ID_DRAW_OPIS                    14
#define ID_DRAW_KOLOR                   15
#define ID_DRAW_SELECT                  16
#define ID_DRAW_CAPTION                 17
#define ID_DRAW_DEADLINE                18
#define ID_DRAW_SPACELOCKED             19
#define ID_SORT_LP                      20
#define ID_SORT_STR                     21
#define ID_SORT_NREPS                   22
#define ID_SORT_NAZWA                   23
#define ID_SORT_ROZMIAR                 24
#define ID_SORT_WARLOG                  25
#define ID_SORT_NR                      26
#define ID_SORT                         27
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDP_OLE_INIT_FAILED             101
#define IDP_FAILED_TO_CREATE            102
#define IDC_PENCIL                      102
#define IDD_KOLUMNY                     102
#define IDD_PAGE                        103
#define IDC_ILEKOLUMN                   104
#define IDD_ADD                         104
#define IDC_KOLOR                       105
#define IDD_INFO                        105
#define IDC_DRZEWO                      105
#define IDC_RZYMSKA                     106
#define IDD_OPIS                        106
#define IDC_NR                          107
#define IDC_CAPTION                     108
#define IDC_BASE_NR                     108
#define IDC_NAME                        109
#define IDC_NAZWA                       110
#define IDD_CUSTZOOM                    110
#define IDC_WYDAWCA                     110
#define ID_NREPS                        111
#define IDD_DB_ADD                      111
#define IDC_LOGPAGE                     112
#define IDC_LOCK                        112
#define ID_PROWADZ1                     112
#define IDD_DBKOLUMNY                   112
#define IDC_SIZEY                       113
#define ID_GAZETA                       113
#define IDD_DRZEWO                      113
#define IDC_SIZEX                       114
#define ID_DATA                         114
#define IDD_DB_OPEN                     114
#define IDC_FIZPAGE                     115
#define IDD_DB_SAVEAS                   115
#define ID_DATA_WYKUPU                  115
#define IDC_LOCKED                      116
#define ID_DATA_ZAMKNIECIA              116
#define IDC_POSX                        117
#define ID_DATA_DEADLINE                117
#define IDC_POSY                        118
#define ID_DATA_STUDIO                  118
#define IDC_TXTPOSY                     119
#define IDC_TXTPOSX                     120
#define ID_PROWADZ2                     121
#define IDC_REMARKS                     121
#define ID_SEKRETARZ                    122
#define IDC_OPIS                        122
#define IDC_WERSJA                      122
#define IDC_FLAGA_REZERW                123
#define ID_KTO_MAKIETUJE                123
#define ID_SPACER_IDA                   124
#define IDC_EPSOK                       125
#define IDC_ZAGROZONE                   126
#define ID_OLDADNO                      127
#define IDC_SP                          128
#define IDC_SPA                         129
#define IDC_MODELID                     130
#define IDD_OPCJE                       133
#define IDC_DEADLINE                    134
#define IDD_ADDDESC                     135
#define IDC_RED                         136
#define IDD_WAIT                        137
#define IDC_FOT                         137
#define IDD_ADD_FIND                    138
#define ID_PAP                          145
#define IDD_INFOLIB                     146
#define ID_MUTACJA                      147
#define IDD_CONFIG                      147
#define IDC_NAMECOMBO                   148
#define ID_STRLOG                       148
#define IDC_CAPTIONCOMBO                149
#define ID_MUTACJA2                     149
#define IDC_FLAG                        150
#define ID_STREFA                       150
#define ID_TYTUL                        151
#define IDC_PRN_MAK                     151
#define IDC_TYTMUT                      152
#define IDC_TYTMUT2                     153
#define IDC_GNAZWA                      153
#define IDC_PASSWD                      153
#define IDD_PASSWD                      153
#define IDC_GEPS                        154
#define IDD_PRNEPS                      154
#define IDC_GWARLOG                     155
#define IDC_GUWAGI                      156
#define IDC_DNAZWA                      157
#define IDC_DEPS                        158
#define IDC_DWARLOG                     159
#define IDD_NOWY_USER                   159
#define IDC_DUWAGI                      160
#define IDC_DBRAK                       161
#define IDD_ACCESS                      161
#define IDC_GCZASKTO                    162
#define IDC_DCZASKTO                    163
#define IDC_GSTUDIO                     164
#define IDC_DSTUDIO                     165
#define IDC_GPLIK                       166
#define IDC_GBRAK                       167
#define IDC_CENA                        168
#define IDC_DPLIK                       168
#define IDC_OBJETOSC                    169
#define IDC_NAKLAD                      170
#define IDC_ISSN                        171
#define IDC_CENA2                       172
#define IDC_NUMERROK                    173
#define IDC_NUMER                       174
#define IDC_KRATKA                      175
#define IDC_SPLIT_CNT                   175
#define IDC_NIEMAKIETUJ                 177
#define IDC_KRATOWE                     178
#define IDC_TYP_OGL                     179
#define ID_GODZ_WYKUPU                  180
#define ID_GODZ_DEADLINE                181
#define ID_GODZ_ZAMKNIECIA              182
#define IDC_MODRED                      183
#define IDC_MODWOL                      184
#define IDC_MODREZ                      185
#define IDC_MODOGL                      186
#define IDC_MODSTATISTICS               187
#define IDC_LIB                         188
#define IDC_MODOGLP                     188
#define IDD_GRIDFORM                    188
#define ID_WERSJA_TEXT                  189
#define IDC_MODREDP                     189
#define IDC_MODWOLP                     190
#define IDC_MAKIETA                     190
#define IDC_MODREZ2                     191
#define IDC_WERSJE_LIB                  192
#define IDC_MODCNT                      192
#define IDC_QUECNT                      193
#define IDC_OPIS_LIB                    194
#define ID_GODZ_STUDIO                  194
#define IDC_SIGN_TEXT                   195
#define IDD_CONNDLG                     195
#define IDC_STRCNT                      196
#define IDD_NOWY_TYTUL                  196
#define IDC_A3_PAGE                     197
#define IDD_SPACER                      197
#define IDC_A4_PAGE                     198
#define ID_DATA_TEXT                    199
#define IDC_MAKDOKUPY                   200
#define ID_DATA_TEXT2                   200
#define IDC_MAKOUTER                    201
#define IDD_EPSDATE                     201
#define IDC_MAKALL                      202
#define IDB_SMALLICONS                  203
#define IDB_STATEICONS                  204
#define IDC_HASHING                     205
#define IDC_DATA_CZOB                   205
#define IDC_GODZ_CZOB                   206
#define IDD_DIRDAYS                     206
#define IDC_ALWAYS                      207
#define IDD_MANCHAT                     207
#define IDC_SPRZEDAL                    208
#define IDC_POWT                        209
#define IDI_INSERT                      209
#define IDD_GRZBIET                     210
#define IDC_EPSSTR                      211
#define IDC_OLDPASS                     211
#define IDC_OGLSTR                      212
#define IDC_NEWPASS                     212
#define IDD_PAGEDERV                    212
#define IDC_NEWPASS2                    213
#define IDC_PREV                        214
#define IDR_MENUGRZBIET                 214
#define IDC_ZAKRES                      215
#define IDR_MENUMUTCZAS                 215
#define IDC_ALLPAGES                    216
#define IDD_KRATCALC                    216
#define IDC_TOPAGE                      217
#define IDD_ACCGRB                      217
#define IDC_FROMPAGE                    218
#define IDC_FMTEPS                      219
#define IDD_ATEXADDS                    219
#define IDC_SUBDIR                      220
#define IDC_FMTPS                       220
#define IDC_CLIENT                      221
#define IDC_SEND                        221
#define IDC_SIGNALL                     222
#define IDC_MARKFOUND                   223
#define IDC_IMIE                        224
#define IDC_FMTPDF                      224
#define IDC_NAZWISKO                    225
#define IDB_ZNACZKI                     225
#define IDC_LOGINNAME                   226
#define IDD_ACDEAD                      226
#define IDC_TELEFON                     227
#define IDC_TYTUL                       227
#define IDC_GRUPA                       228
#define IDC_MUTACJA                     228
#define IDC_UWAGI                       229
#define IDC_ALLTYT                      229
#define IDC_PASS                        230
#define IDC_RACC                        230
#define IDC_WACC                        231
#define IDC_DACC                        232
#define IDV_COMBO_COLOR                 233
#define IDC_SENIOR                      233
#define IDV_COMBO_HEAD                  234
#define IDC_SACC                        234
#define IDC_PACC                        235
#define IDC_GACC                        236
#define IDC_GAZETA                      255
#define IDC_PRN_FUN                     256
#define IDC_YESNNEXT                    266
#define IDC_ALIKE                       267
#define IDC_SETDEA                      269
#define IDC_EMISJE                      270
#define IDC_LASTEMISION                 271
#define IDC_KROK                        272
#define IDC_EXACTPLACE                  273
#define IDC_PAGEPARITY                  274
#define IDC_DT                          274
#define IDC_PAGELAYOUT                  275
#define IDC_WSEKCJI                     276
#define IDC_SEKCJA                      277
#define IDC_DEALAPPEND                  278
#define IDC_SPACER                      284
#define IDC_DBTEST                      285
#define IDC_CBDRUK                      286
#define IDC_CBRIP                       287
#define IDC_CBPOWT                      292
#define IDC_DAYDIRS                     293
#define IDC_COPYOLDEPS                  294
#define IDC_PODWALY                     295
#define IDC_STUDIO                      298
#define IDC_MEMSTAT                     302
#define IDC_GRZBIET                     305
#define IDC_PODSUBDIR                   306
#define IDC_INSERT                      307
#define IDC_WHERE                       308
#define IDC_OPIMODE                     308
#define IDC_USUN                        309
#define IDC_DERVLVL                     310
#define IDC_PRINTHOUSE                  311
#define IDC_DERVINFO                    312
#define IDC_MUTRED                      313
#define IDC_DEADLINEDAY                 314
#define IDC_DODAJ                       315
#define IDC_SZYJ                        316
#define IDZDNIA                         317
#define IDC_SPINX                       319
#define IDC_SPINY                       320
#define IDC_PRINT_LDRZ                  323
#define IDC_PRINT_CDRZ                  324
#define IDC_PRINT_ORG                   325
#define IDC_CKPLDRZ                     328
#define IDC_SUBSET                      328
#define IDC_CKPCDRZ                     329
#define IDC_CKPORG                      330
#define IDC_ADDLIST                     330
#define IDC_TYP_PAPIERU                 335
#define IDC_OL                          336
#define IDC_PAPIER                      340
#define IDC_ODBLOKUJ                    342
#define IDC_PAP                         344
#define IDC_OKRES                       345
#define IDC_DATY                        346
#define IDC_TOP                         351
#define IDC_BOTTOM                      352
#define IDC_PUBLIST                     353
#define IDC_LEFT                        354
#define IDB_DODAJ                       355
#define IDC_RIGHT                       357
#define IDC_PAGESPERROW                 359
#define IDC_ROZKLAD                     360
#define IDC_KOL                         361
#define IDC_ACDEAD                      362
#define IDC_SZYCIE                      364
#define IDC_ZAJAWKA                     366
#define IDC_EPSDATE                     367
#define IDC_NAGL_RED                    368
#define IDC_DIR_UZU                     369
#define ID_VIEW_CUST_TLB                370
#define IDR_TOOL_MAIN                   371
#define IDC_EPS_SRC                     380
#define IDC_EPS_OLD                     381
#define IDC_EPS_DST                     382
#define IDC_PS_DST                      383
#define IDC_EPS_ZAJ                     384
#define IDC_EPS_POD                     385
#define IDC_EPS_DRO                     386
#define IDC_EPS_IRF                     387
#define IDC_EPS_UZU                     388
#define IDC_EPS_KOK                     389
#define ID_ADD_FIND                     16384
#define ID_DRAW_OPCJE                   16385
#define ID_FILE_PRINT_1P                16386
#define ID_FILE_DRZEWO                  16387
#define ID_FILE_INFO                    16388
#define ID_FILE_NEW_BATH                16389
#define ID_FILE_PRINT_PREVIEW_1P        16390
#define ID_DRAW_PAGE                    16391
#define ID_DRAW_NUMEROWANIE             16392
#define ID_VIEW_PAGEFONT                16393
#define ID_VIEW_ADDFONT                 16394
#define ID_VIEW_LUPKA_PLUS              16404
#define ID_VIEW_LUPKA_MINUS             16405
#define IDM_ASIDE_ADDS                  16406
#define ID_VIEW_ZOOM100                 32759
#define ID_VIEW_ZOOM125                 32760
#define ID_VIEW_ZOOM150                 32761
#define ID_VIEW_ZOOM200                 32762
#define ID_VIEW_ZOOM250                 32763
#define ID_VIEW_ZOOM300                 32764
#define ID_VIEW_ZOOM400                 32765
#define ID_VIEW_ZOOM500                 32766
#define ID_VIEW_ZOOM750                 32767
#define ID_VIEW_ZOOMCUSTOM              32768
#define ID_CANCEL_EDIT                  32769
#define ID_OBJECT_MOVETOFRONT           32770
#define ID_OBJECT_MOVETOBACK            32778
#define ID_OBJECT_MOVEFORWARD           32779
#define ID_OBJECT_MOVEBACK              32780
#define ID_VIEW_SHOWOBJECTS             32784
#define ID_EDIT_PROPERTIES              32785
#define ID_ADD_IMPORT                   32789
#define ID_ADD_EXPORT                   32790
#define ID_CHOOSE_FONT                  32797
#define ID_ADD_IMPORTADD                32807
#define ID_ADD_IMPORTPLUS               32808
#define ID_FILE_SAVE_AS_PRN             32826
#define ID_ADD_OPCJE                    32828
#define ID_EDIT_EPSSIZE                 32834
#define ID_VIEW_SPACELOCKS              32837
#define ID_ADD_DBIMPORT                 32852
#define ID_ADD_DBIMPORTPLUS             32853
#define ID_ADD_DBIMPORTMINUS            32855
#define ID_FILE_DBOPEN                  32856
#define ID_FILE_DBSAVE                  32857
#define ID_FILE_DBSAVE_AS               32859
#define ID_FILE_DBDELETE                32861
#define ID_VU_MAKIETOWANIE              32862
#define ID_VU_MAK_STRONY                32863
#define ID_VU_CK_MAKIETOWANIE           32864
#define ID_ADD_IMPORTMINUS              32865
#define ID_VIEW_ADDDESC                 32866
#define ID_LOGIN                        32868
#define ID_FILE_REFRESH                 32871
#define ID_FILE_DBOPENRO                32875
#define ID_VU_MAKDOKUPY                 32877
#define ID_ADD_SYNCHRONIZE              32878
#define ID_VIEW_CZASOBOW                32882
#define ID_FILE_PRINT_EPS               32883
#define ID_CHECK_EPS                    32884
#define IDM_PASSWD                      32886
#define IDM_EDIT_FIND_NEXT              32888
#define IDM_KRATA_ADD                   32899
#define IDM_KRATA_DEL                   32900
#define IDM_KRATA_SEL                   32901
#define IDM_USERMAN                     32902
#define IDM_NEWUSER                     32903
#define IDM_ACCESS                      32904
#define IDM_NEWTITLE                    32905
#define IDM_CAPTIONS                    32906
#define IDM_VIEW_STUDIO                 32907
#define ID_INDICATOR_LOGIN              32910
#define IDM_SHOWREPT                    32911
#define IDM_SYNCPOW                     32912
#define ID_INDICATOR_OPENSTAT           32913
#define ID_POMOC                        32915
#define IDM_DELREMARKS                  32917
#define IDM_CHECKREP                    32918
#define IDM_EPSDATA                     32919
#define IDM_DAYDIRS                     32920
#define IDM_SENDMSG                     32921
#define IDM_SHOWDTLS                    32922
#define IDM_PAGEDERV                    32923
#define IDM_INSERTGRZBIET               32924
#define IDC_DELETEINSERT                32925
#define IDM_INCMUTCZAS                  32927
#define IDM_DECMUTCZAS                  32930
#define IDM_SYNCDRV                     32931
#define IDM_SETPAGINA                   32934
#define ID_INDICATOR_ROLE               32935
#define IDM_SETDEA                      32936
#define IDM_SHOWTIME                    32937
#define IDM_IRFAN                       32938
#define ID_NARZ_KALKULATORKRAT          32939
#define IDM_ACCGRB                      32940
#define IDM_PREVPDF                     32947
#define ID_WIDOK_CHCAP                  32951
#define IDM_CHANGEVIEW                  32952
#define IDM_ATEXSYG                     32953
#define ID_FILE_PRINT_ALL               32955
#define ID_FILE_PRINT_PREVIEW_ALL       32956
#define IDM_ACDEAD                      32957
#define IDM_PREV_KOR                    32958
#define ID_WIDOK_COLPERROW              32959
#define IDM_PREVDIG                     32962
#define IDS_ARCH_URL                    40000
#define IDS_INITVUPDF                   40001
#define IDS_INITVUPDF2                  40002
#define IDS_OPISEPAR                    40003
#define IDS_DB_PD                       40004
#define IDS_DB_TP                       40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        373
#define _APS_NEXT_COMMAND_VALUE         32963
#define _APS_NEXT_CONTROL_VALUE         390
#define _APS_NEXT_SYMED_VALUE           143
#endif
#endif
